spring:
  data:
    elasticsearch:
      # cluster-nodes: localhost:9200
      # cluster-name: elasticsearch
      cluster-nodes: elasticsearch-0.elasticsearch:9200
      cluster-name: elasticsearch-v2