spring:
  data:
    elasticsearch:
      # cluster-nodes: elasticsearch-0.elasticsearch.elasticsearch.svc.cluster.local:9200
      # cluster-name: elasticsearch-v2
      cluster-nodes: elasticsearch-0.elasticsearch:9200
      cluster-name: elasticsearch-v2